# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 464)
        Form.setMinimumSize(QtCore.QSize(900, 300))
        Form.setMaximumSize(QtCore.QSize(2000, 1000))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.regLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.regLabel.sizePolicy().hasHeightForWidth())
        self.regLabel.setSizePolicy(sizePolicy)
        self.regLabel.setMinimumSize(QtCore.QSize(10, 50))
        self.regLabel.setMaximumSize(QtCore.QSize(20, 262))
        self.regLabel.setBaseSize(QtCore.QSize(0, 5))
        self.regLabel.setStyleSheet("background : green;")
        self.regLabel.setText("")
        self.regLabel.setObjectName("regLabel")
        self.horizontalLayout_2.addWidget(self.regLabel)
        self.regCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.regCheckBox.setFont(font)
        self.regCheckBox.setObjectName("regCheckBox")
        self.horizontalLayout_2.addWidget(self.regCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.N4Label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.N4Label.sizePolicy().hasHeightForWidth())
        self.N4Label.setSizePolicy(sizePolicy)
        self.N4Label.setMinimumSize(QtCore.QSize(10, 50))
        self.N4Label.setMaximumSize(QtCore.QSize(20, 262))
        self.N4Label.setBaseSize(QtCore.QSize(0, 5))
        self.N4Label.setStyleSheet("background : green;")
        self.N4Label.setText("")
        self.N4Label.setObjectName("N4Label")
        self.horizontalLayout_4.addWidget(self.N4Label)
        self.N4CheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.N4CheckBox.setFont(font)
        self.N4CheckBox.setObjectName("N4CheckBox")
        self.horizontalLayout_4.addWidget(self.N4CheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.betLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.betLabel.sizePolicy().hasHeightForWidth())
        self.betLabel.setSizePolicy(sizePolicy)
        self.betLabel.setMinimumSize(QtCore.QSize(10, 15))
        self.betLabel.setMaximumSize(QtCore.QSize(20, 62626))
        self.betLabel.setBaseSize(QtCore.QSize(0, 5))
        self.betLabel.setStyleSheet("background : green;")
        self.betLabel.setText("")
        self.betLabel.setObjectName("betLabel")
        self.horizontalLayout_3.addWidget(self.betLabel)
        self.betCheckBox = QtWidgets.QCheckBox(Form)
        self.betCheckBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.betCheckBox.setFont(font)
        self.betCheckBox.setObjectName("betCheckBox")
        self.horizontalLayout_3.addWidget(self.betCheckBox)
        self.NorCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NorCheckBox.setFont(font)
        self.NorCheckBox.setObjectName("NorCheckBox")
        self.horizontalLayout_3.addWidget(self.NorCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.segLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.segLabel.sizePolicy().hasHeightForWidth())
        self.segLabel.setSizePolicy(sizePolicy)
        self.segLabel.setMinimumSize(QtCore.QSize(20, 15))
        self.segLabel.setMaximumSize(QtCore.QSize(20, 62626))
        self.segLabel.setBaseSize(QtCore.QSize(0, 5))
        self.segLabel.setStyleSheet("background : green;")
        self.segLabel.setText("")
        self.segLabel.setObjectName("segLabel")
        self.horizontalLayout_5.addWidget(self.segLabel)
        self.HsCheckBox = QtWidgets.QCheckBox(Form)
        self.HsCheckBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.HsCheckBox.setFont(font)
        self.HsCheckBox.setObjectName("HsCheckBox")
        self.horizontalLayout_5.addWidget(self.HsCheckBox)
        self.BsCheckBox_2 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.BsCheckBox_2.setFont(font)
        self.BsCheckBox_2.setObjectName("BsCheckBox_2")
        self.horizontalLayout_5.addWidget(self.BsCheckBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FeatureLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FeatureLabel.sizePolicy().hasHeightForWidth())
        self.FeatureLabel.setSizePolicy(sizePolicy)
        self.FeatureLabel.setMinimumSize(QtCore.QSize(10, 15))
        self.FeatureLabel.setMaximumSize(QtCore.QSize(20, 62626))
        self.FeatureLabel.setBaseSize(QtCore.QSize(0, 5))
        self.FeatureLabel.setStyleSheet("background : green;")
        self.FeatureLabel.setText("")
        self.FeatureLabel.setObjectName("FeatureLabel")
        self.horizontalLayout_6.addWidget(self.FeatureLabel)
        self.FeatureCheckBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.FeatureCheckBox.setFont(font)
        self.FeatureCheckBox.setObjectName("FeatureCheckBox")
        self.horizontalLayout_6.addWidget(self.FeatureCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dataLabel_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataLabel_2.sizePolicy().hasHeightForWidth())
        self.dataLabel_2.setSizePolicy(sizePolicy)
        self.dataLabel_2.setMinimumSize(QtCore.QSize(10, 15))
        self.dataLabel_2.setMaximumSize(QtCore.QSize(20, 62626))
        self.dataLabel_2.setBaseSize(QtCore.QSize(0, 5))
        self.dataLabel_2.setStyleSheet("background : gray;")
        self.dataLabel_2.setText("")
        self.dataLabel_2.setObjectName("dataLabel_2")
        self.horizontalLayout_8.addWidget(self.dataLabel_2)
        self.dataCheckBox_2 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dataCheckBox_2.setFont(font)
        self.dataCheckBox_2.setObjectName("dataCheckBox_2")
        self.horizontalLayout_8.addWidget(self.dataCheckBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(3, 20))
        self.frame.setMaximumSize(QtCore.QSize(3, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background:#dbdbdb;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setLineWidth(2)
        self.table.setMidLineWidth(0)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setAutoScroll(True)
        self.table.setRowCount(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setMinimumSectionSize(20)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setCascadingSectionResizes(True)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table)
        self.runLabel = QtWidgets.QLabel(Form)
        self.runLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.runLabel.setObjectName("runLabel")
        self.verticalLayout.addWidget(self.runLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chooseButton = QtWidgets.QPushButton(Form)
        self.chooseButton.setMinimumSize(QtCore.QSize(120, 30))
        self.chooseButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chooseButton.setFont(font)
        self.chooseButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chooseButton.setAutoFillBackground(False)
        self.chooseButton.setStyleSheet("")
        self.chooseButton.setObjectName("chooseButton")
        self.horizontalLayout.addWidget(self.chooseButton)
        self.chooseOutButton = QtWidgets.QPushButton(Form)
        self.chooseOutButton.setMinimumSize(QtCore.QSize(120, 30))
        self.chooseOutButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chooseOutButton.setFont(font)
        self.chooseOutButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chooseOutButton.setObjectName("chooseOutButton")
        self.horizontalLayout.addWidget(self.chooseOutButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(300, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.startButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(0, 0))
        self.startButton.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("margin:10 30;")
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Batch"))
        self.regCheckBox.setText(_translate("Form", "Registration"))
        self.N4CheckBox.setText(_translate("Form", "N4 Correction"))
        self.betCheckBox.setText(_translate("Form", "Brain Extration"))
        self.NorCheckBox.setText(_translate("Form", "Normalise"))
        self.HsCheckBox.setText(_translate("Form", "Hippocumps Segmentation"))
        self.BsCheckBox_2.setText(_translate("Form", "Brian Segmentation"))
        self.FeatureCheckBox.setText(_translate("Form", "Feature"))
        self.dataCheckBox_2.setText(_translate("Form", "Data Analysis"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Status"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Path"))
        self.runLabel.setText(_translate("Form", "not running"))
        self.chooseButton.setText(_translate("Form", "Choose Input Dir"))
        self.chooseOutButton.setText(_translate("Form", "Choose Out Dir"))
        self.startButton.setText(_translate("Form", "Start!"))

from . import resource_rc
