# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchUI_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1030, 685)
        Form.setMinimumSize(QtCore.QSize(900, 300))
        Form.setMaximumSize(QtCore.QSize(2000, 1000))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ProcessWidget = QtWidgets.QWidget(Form)
        self.ProcessWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.ProcessWidget.setObjectName("ProcessWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ProcessWidget)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PreprocessingcheckBox = QtWidgets.QCheckBox(self.ProcessWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PreprocessingcheckBox.setFont(font)
        self.PreprocessingcheckBox.setChecked(True)
        self.PreprocessingcheckBox.setObjectName("PreprocessingcheckBox")
        self.verticalLayout_4.addWidget(self.PreprocessingcheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.regLabel = QtWidgets.QLabel(self.ProcessWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.regLabel.sizePolicy().hasHeightForWidth())
        self.regLabel.setSizePolicy(sizePolicy)
        self.regLabel.setMinimumSize(QtCore.QSize(10, 50))
        self.regLabel.setMaximumSize(QtCore.QSize(20, 262))
        self.regLabel.setBaseSize(QtCore.QSize(0, 5))
        self.regLabel.setStyleSheet("background : green;")
        self.regLabel.setText("")
        self.regLabel.setObjectName("regLabel")
        self.horizontalLayout_2.addWidget(self.regLabel)
        self.regCheckBox = QtWidgets.QCheckBox(self.ProcessWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.regCheckBox.setFont(font)
        self.regCheckBox.setChecked(True)
        self.regCheckBox.setObjectName("regCheckBox")
        self.horizontalLayout_2.addWidget(self.regCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.N4Label = QtWidgets.QLabel(self.ProcessWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.N4Label.sizePolicy().hasHeightForWidth())
        self.N4Label.setSizePolicy(sizePolicy)
        self.N4Label.setMinimumSize(QtCore.QSize(10, 50))
        self.N4Label.setMaximumSize(QtCore.QSize(20, 262))
        self.N4Label.setBaseSize(QtCore.QSize(0, 5))
        self.N4Label.setStyleSheet("background : green;")
        self.N4Label.setText("")
        self.N4Label.setObjectName("N4Label")
        self.horizontalLayout_4.addWidget(self.N4Label)
        self.N4CheckBox = QtWidgets.QCheckBox(self.ProcessWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.N4CheckBox.setFont(font)
        self.N4CheckBox.setChecked(True)
        self.N4CheckBox.setObjectName("N4CheckBox")
        self.horizontalLayout_4.addWidget(self.N4CheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.betLabel = QtWidgets.QLabel(self.ProcessWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.betLabel.sizePolicy().hasHeightForWidth())
        self.betLabel.setSizePolicy(sizePolicy)
        self.betLabel.setMinimumSize(QtCore.QSize(20, 50))
        self.betLabel.setMaximumSize(QtCore.QSize(20, 50))
        self.betLabel.setBaseSize(QtCore.QSize(0, 5))
        self.betLabel.setStyleSheet("background : green;")
        self.betLabel.setText("")
        self.betLabel.setObjectName("betLabel")
        self.horizontalLayout_3.addWidget(self.betLabel)
        self.betCheckBox = QtWidgets.QCheckBox(self.ProcessWidget)
        self.betCheckBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.betCheckBox.setFont(font)
        self.betCheckBox.setChecked(True)
        self.betCheckBox.setObjectName("betCheckBox")
        self.horizontalLayout_3.addWidget(self.betCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.ProcessWidget)
        self.SegWidget = QtWidgets.QWidget(Form)
        self.SegWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.SegWidget.setObjectName("SegWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SegWidget)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SegCheckBox = QtWidgets.QCheckBox(self.SegWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.SegCheckBox.setFont(font)
        self.SegCheckBox.setChecked(True)
        self.SegCheckBox.setObjectName("SegCheckBox")
        self.verticalLayout_5.addWidget(self.SegCheckBox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.betLabel_2 = QtWidgets.QLabel(self.SegWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.betLabel_2.sizePolicy().hasHeightForWidth())
        self.betLabel_2.setSizePolicy(sizePolicy)
        self.betLabel_2.setMinimumSize(QtCore.QSize(20, 50))
        self.betLabel_2.setMaximumSize(QtCore.QSize(20, 50))
        self.betLabel_2.setBaseSize(QtCore.QSize(0, 5))
        self.betLabel_2.setStyleSheet("background : green;")
        self.betLabel_2.setText("")
        self.betLabel_2.setObjectName("betLabel_2")
        self.horizontalLayout_9.addWidget(self.betLabel_2)
        self.HsCheckBox = QtWidgets.QCheckBox(self.SegWidget)
        self.HsCheckBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.HsCheckBox.setFont(font)
        self.HsCheckBox.setChecked(True)
        self.HsCheckBox.setObjectName("HsCheckBox")
        self.horizontalLayout_9.addWidget(self.HsCheckBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.segLabel = QtWidgets.QLabel(self.SegWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.segLabel.sizePolicy().hasHeightForWidth())
        self.segLabel.setSizePolicy(sizePolicy)
        self.segLabel.setMinimumSize(QtCore.QSize(20, 50))
        self.segLabel.setMaximumSize(QtCore.QSize(20, 50))
        self.segLabel.setBaseSize(QtCore.QSize(0, 5))
        self.segLabel.setStyleSheet("background : green;")
        self.segLabel.setText("")
        self.segLabel.setObjectName("segLabel")
        self.horizontalLayout_5.addWidget(self.segLabel)
        self.BsCheckBox_2 = QtWidgets.QCheckBox(self.SegWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.BsCheckBox_2.setFont(font)
        self.BsCheckBox_2.setChecked(True)
        self.BsCheckBox_2.setObjectName("BsCheckBox_2")
        self.horizontalLayout_5.addWidget(self.BsCheckBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.SegWidget)
        self.AnalysisWidget = QtWidgets.QWidget(Form)
        self.AnalysisWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.AnalysisWidget.setObjectName("AnalysisWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.AnalysisWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AnalysisCheckBox = QtWidgets.QCheckBox(self.AnalysisWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AnalysisCheckBox.setFont(font)
        self.AnalysisCheckBox.setObjectName("AnalysisCheckBox")
        self.gridLayout_2.addWidget(self.AnalysisCheckBox, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FeatureLabel = QtWidgets.QLabel(self.AnalysisWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FeatureLabel.sizePolicy().hasHeightForWidth())
        self.FeatureLabel.setSizePolicy(sizePolicy)
        self.FeatureLabel.setMinimumSize(QtCore.QSize(10, 15))
        self.FeatureLabel.setMaximumSize(QtCore.QSize(20, 50))
        self.FeatureLabel.setBaseSize(QtCore.QSize(0, 5))
        self.FeatureLabel.setStyleSheet("background : green;")
        self.FeatureLabel.setText("")
        self.FeatureLabel.setObjectName("FeatureLabel")
        self.horizontalLayout_6.addWidget(self.FeatureLabel)
        self.FeatureCheckBox = QtWidgets.QCheckBox(self.AnalysisWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.FeatureCheckBox.setFont(font)
        self.FeatureCheckBox.setChecked(True)
        self.FeatureCheckBox.setAutoRepeat(False)
        self.FeatureCheckBox.setObjectName("FeatureCheckBox")
        self.horizontalLayout_6.addWidget(self.FeatureCheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dataLabel_2 = QtWidgets.QLabel(self.AnalysisWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dataLabel_2.sizePolicy().hasHeightForWidth())
        self.dataLabel_2.setSizePolicy(sizePolicy)
        self.dataLabel_2.setMinimumSize(QtCore.QSize(10, 15))
        self.dataLabel_2.setMaximumSize(QtCore.QSize(20, 50))
        self.dataLabel_2.setBaseSize(QtCore.QSize(0, 5))
        self.dataLabel_2.setStyleSheet("background : gray;")
        self.dataLabel_2.setText("")
        self.dataLabel_2.setObjectName("dataLabel_2")
        self.horizontalLayout_8.addWidget(self.dataLabel_2)
        self.dataCheckBox_2 = QtWidgets.QCheckBox(self.AnalysisWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.dataCheckBox_2.setFont(font)
        self.dataCheckBox_2.setObjectName("dataCheckBox_2")
        self.horizontalLayout_8.addWidget(self.dataCheckBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.AnalysisWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(3, 20))
        self.frame.setMaximumSize(QtCore.QSize(3, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background:#dbdbdb;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setLineWidth(2)
        self.table.setMidLineWidth(0)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setAutoScroll(True)
        self.table.setRowCount(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setMinimumSectionSize(20)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setCascadingSectionResizes(True)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.table)
        self.runLabel = QtWidgets.QLabel(Form)
        self.runLabel.setMinimumSize(QtCore.QSize(0, 50))
        self.runLabel.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.runLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.runLabel.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color:gray;")
        self.runLabel.setObjectName("runLabel")
        self.verticalLayout.addWidget(self.runLabel)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(300, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.chooseInputButton = QtWidgets.QToolButton(Form)
        self.chooseInputButton.setObjectName("chooseInputButton")
        self.horizontalLayout.addWidget(self.chooseInputButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.chooseOutputButton = QtWidgets.QToolButton(Form)
        self.chooseOutputButton.setObjectName("chooseOutputButton")
        self.horizontalLayout_7.addWidget(self.chooseOutputButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setMinimumSize(QtCore.QSize(150, 40))
        self.startButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Batch"))
        self.PreprocessingcheckBox.setText(_translate("Form", "Preprocessing"))
        self.regCheckBox.setText(_translate("Form", "Registration"))
        self.N4CheckBox.setText(_translate("Form", "N4 Correction"))
        self.betCheckBox.setText(_translate("Form", "Brain Extration"))
        self.SegCheckBox.setText(_translate("Form", "Segmentation"))
        self.HsCheckBox.setText(_translate("Form", "Hippocumps Segmentation"))
        self.BsCheckBox_2.setText(_translate("Form", "Brian Segmentation"))
        self.AnalysisCheckBox.setText(_translate("Form", "Analysis"))
        self.FeatureCheckBox.setText(_translate("Form", "Feature"))
        self.dataCheckBox_2.setText(_translate("Form", "Data Analysis"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Status"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Path"))
        self.runLabel.setText(_translate("Form", "not running"))
        self.label.setText(_translate("Form", "Input Directory"))
        self.chooseInputButton.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Output Directory"))
        self.chooseOutputButton.setText(_translate("Form", "..."))
        self.startButton.setText(_translate("Form", "Start!"))

from . import resource_rc
