# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bfcUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BrainExtraction(object):
    def setupUi(self, BrainExtraction):
        BrainExtraction.setObjectName("BrainExtraction")
        BrainExtraction.resize(414, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BrainExtraction.sizePolicy().hasHeightForWidth())
        BrainExtraction.setSizePolicy(sizePolicy)
        BrainExtraction.setMaximumSize(QtCore.QSize(1000, 1000))
        BrainExtraction.setLayoutDirection(QtCore.Qt.LeftToRight)
        BrainExtraction.setAutoFillBackground(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(BrainExtraction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RadioSingle = QtWidgets.QRadioButton(BrainExtraction)
        self.RadioSingle.setObjectName("RadioSingle")
        self.buttonGroup = QtWidgets.QButtonGroup(BrainExtraction)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.RadioSingle)
        self.horizontalLayout_3.addWidget(self.RadioSingle)
        self.RadioDir = QtWidgets.QRadioButton(BrainExtraction)
        self.RadioDir.setObjectName("RadioDir")
        self.buttonGroup.addButton(self.RadioDir)
        self.horizontalLayout_3.addWidget(self.RadioDir)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(BrainExtraction)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LineFile = QtWidgets.QLineEdit(BrainExtraction)
        self.LineFile.setObjectName("LineFile")
        self.horizontalLayout.addWidget(self.LineFile)
        self.BtnChooseFile = QtWidgets.QToolButton(BrainExtraction)
        self.BtnChooseFile.setObjectName("BtnChooseFile")
        self.horizontalLayout.addWidget(self.BtnChooseFile)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(BrainExtraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.LineOutput = QtWidgets.QLineEdit(BrainExtraction)
        self.LineOutput.setObjectName("LineOutput")
        self.horizontalLayout_2.addWidget(self.LineOutput)
        self.BtnChooseOutput = QtWidgets.QToolButton(BrainExtraction)
        self.BtnChooseOutput.setObjectName("BtnChooseOutput")
        self.horizontalLayout_2.addWidget(self.BtnChooseOutput)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(40)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CheckBFC = QtWidgets.QCheckBox(BrainExtraction)
        self.CheckBFC.setObjectName("CheckBFC")
        self.horizontalLayout_4.addWidget(self.CheckBFC)
        self.CheckNorm = QtWidgets.QCheckBox(BrainExtraction)
        self.CheckNorm.setObjectName("CheckNorm")
        self.horizontalLayout_4.addWidget(self.CheckNorm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(BrainExtraction)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.BtnStart = QtWidgets.QPushButton(BrainExtraction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnStart.sizePolicy().hasHeightForWidth())
        self.BtnStart.setSizePolicy(sizePolicy)
        self.BtnStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BtnStart.setObjectName("BtnStart")
        self.verticalLayout.addWidget(self.BtnStart)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(BrainExtraction)
        QtCore.QMetaObject.connectSlotsByName(BrainExtraction)

    def retranslateUi(self, BrainExtraction):
        _translate = QtCore.QCoreApplication.translate
        BrainExtraction.setWindowTitle(_translate("BrainExtraction", "Bias Field Correction"))
        self.RadioSingle.setText(_translate("BrainExtraction", "SingleFile"))
        self.RadioDir.setText(_translate("BrainExtraction", "Director Bath"))
        self.label.setText(_translate("BrainExtraction", "Image Path:"))
        self.BtnChooseFile.setText(_translate("BrainExtraction", "..."))
        self.label_2.setText(_translate("BrainExtraction", "Output Path:"))
        self.BtnChooseOutput.setText(_translate("BrainExtraction", "..."))
        self.CheckBFC.setText(_translate("BrainExtraction", "N4 Bias Field Correction"))
        self.CheckNorm.setText(_translate("BrainExtraction", "Normalize"))
        self.label_3.setText(_translate("BrainExtraction", "Note:this tool not support 4D image"))
        self.BtnStart.setText(_translate("BrainExtraction", "Start Calculate!"))

