# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dicom.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from Core import dicom2nii
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal,QThread
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 120)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dicomLt = QtWidgets.QLineEdit(self.layoutWidget)
        self.dicomLt.setObjectName("dicomLt")
        self.gridLayout_3.addWidget(self.dicomLt, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(20, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dicomBtn = QtWidgets.QPushButton(self.frame)
        self.dicomBtn.setGeometry(QtCore.QRect(0, 0, 18, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dicomBtn.sizePolicy().hasHeightForWidth())
        self.dicomBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(False)
        font.setWeight(50)
        self.dicomBtn.setFont(font)
        self.dicomBtn.setIconSize(QtCore.QSize(0, 0))
        self.dicomBtn.setCheckable(False)
        self.dicomBtn.setObjectName("dicomBtn")
        self.gridLayout_3.addWidget(self.frame, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.niiLt = QtWidgets.QLineEdit(self.layoutWidget)
        self.niiLt.setObjectName("niiLt")
        self.gridLayout.addWidget(self.niiLt, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(20, 20))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.NiiBtn = QtWidgets.QPushButton(self.frame_2)
        self.NiiBtn.setGeometry(QtCore.QRect(-1, 0, 18, 20))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.NiiBtn.setFont(font)
        self.NiiBtn.setObjectName("NiiBtn")
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(220, -1, 220, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.dicomLt.setReadOnly(True)
        self.niiLt.setReadOnly(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DicomConvert"))
        self.dicomLt.setText(_translate("Form", "select the dicom dir path"))
        self.label.setText(_translate("Form", "DicomPath"))
        self.dicomBtn.setText(_translate("Form", "..."))
        self.niiLt.setText(_translate("Form", "select the output file"))
        self.label_2.setText(_translate("Form", " NiiPath "))
        self.NiiBtn.setText(_translate("Form", "..."))
        self.startBtn.setText(_translate("Form", "Start"))
        self.dicomBtn.clicked.connect(self.DicomDir)
        self.NiiBtn.clicked.connect(self.NiiDir)
        self.startBtn.clicked.connect(self.Cal)

