# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feature.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Feature(object):
    def setupUi(self, Feature):
        Feature.setObjectName("Feature")
        Feature.resize(606, 256)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Feature)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Feature)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.fileRadiobtn = QtWidgets.QRadioButton(Feature)
        self.fileRadiobtn.setObjectName("fileRadiobtn")
        self.horizontalLayout.addWidget(self.fileRadiobtn)
        self.dirRadiobtn = QtWidgets.QRadioButton(Feature)
        self.dirRadiobtn.setObjectName("dirRadiobtn")
        self.horizontalLayout.addWidget(self.dirRadiobtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Feature)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineTextImage = QtWidgets.QLineEdit(Feature)
        self.lineTextImage.setMinimumSize(QtCore.QSize(250, 0))
        self.lineTextImage.setInputMask("")
        self.lineTextImage.setObjectName("lineTextImage")
        self.horizontalLayout_2.addWidget(self.lineTextImage)
        self.chooseImageBtn = QtWidgets.QToolButton(Feature)
        self.chooseImageBtn.setMinimumSize(QtCore.QSize(15, 0))
        self.chooseImageBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.chooseImageBtn.setObjectName("chooseImageBtn")
        self.horizontalLayout_2.addWidget(self.chooseImageBtn)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Feature)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineTextMask = QtWidgets.QLineEdit(Feature)
        self.lineTextMask.setMinimumSize(QtCore.QSize(250, 0))
        self.lineTextMask.setObjectName("lineTextMask")
        self.horizontalLayout_3.addWidget(self.lineTextMask)
        self.chooseMaskBtn = QtWidgets.QToolButton(Feature)
        self.chooseMaskBtn.setMinimumSize(QtCore.QSize(15, 0))
        self.chooseMaskBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.chooseMaskBtn.setObjectName("chooseMaskBtn")
        self.horizontalLayout_3.addWidget(self.chooseMaskBtn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Feature)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.in3 = QtWidgets.QLineEdit(Feature)
        self.in3.setMinimumSize(QtCore.QSize(250, 0))
        self.in3.setObjectName("in3")
        self.horizontalLayout_4.addWidget(self.in3)
        self.btn3 = QtWidgets.QToolButton(Feature)
        self.btn3.setMinimumSize(QtCore.QSize(15, 0))
        self.btn3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_4.addWidget(self.btn3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pbar = QtWidgets.QProgressBar(Feature)
        self.pbar.setProperty("value", 24)
        self.pbar.setObjectName("pbar")
        self.verticalLayout.addWidget(self.pbar)
        self.btnStart = QtWidgets.QPushButton(Feature)
        self.btnStart.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout.addWidget(self.btnStart, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Feature)
        QtCore.QMetaObject.connectSlotsByName(Feature)

    def retranslateUi(self, Feature):
        _translate = QtCore.QCoreApplication.translate
        Feature.setWindowTitle(_translate("Feature", "Feature"))
        self.label_4.setText(_translate("Feature", "Mode"))
        self.fileRadiobtn.setText(_translate("Feature", "Sigle File"))
        self.dirRadiobtn.setText(_translate("Feature", "Directory Batch"))
        self.label.setText(_translate("Feature", "Image Path"))
        self.lineTextImage.setText(_translate("Feature", "The source Image/Directory Path"))
        self.chooseImageBtn.setText(_translate("Feature", "..."))
        self.label_2.setText(_translate("Feature", "ROI Path"))
        self.lineTextMask.setText(_translate("Feature", "If not,use the default Ref MNI 152"))
        self.chooseMaskBtn.setText(_translate("Feature", "..."))
        self.label_3.setText(_translate("Feature", "Output Path"))
        self.in3.setText(_translate("Feature", "the result Image/Directory Path"))
        self.btn3.setText(_translate("Feature", "..."))
        self.btnStart.setText(_translate("Feature", "Start!"))

