# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(500, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(500, 600))
        MainWindow.setStyleSheet("#frame{border:none}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/newlogo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BtnDicom = QtWidgets.QPushButton(self.groupBox)
        self.BtnDicom.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnDicom.setFont(font)
        self.BtnDicom.setObjectName("BtnDicom")
        self.horizontalLayout.addWidget(self.BtnDicom)
        self.BtnReg = QtWidgets.QPushButton(self.groupBox)
        self.BtnReg.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnReg.setFont(font)
        self.BtnReg.setObjectName("BtnReg")
        self.horizontalLayout.addWidget(self.BtnReg)
        self.BtnBet = QtWidgets.QPushButton(self.groupBox)
        self.BtnBet.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnBet.setFont(font)
        self.BtnBet.setObjectName("BtnBet")
        self.horizontalLayout.addWidget(self.BtnBet)
        self.BFC = QtWidgets.QPushButton(self.groupBox)
        self.BFC.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.BFC.setFont(font)
        self.BFC.setTabletTracking(False)
        self.BFC.setAutoRepeat(False)
        self.BFC.setObjectName("BFC")
        self.horizontalLayout.addWidget(self.BFC)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnSeg = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnSeg.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnSeg.setFont(font)
        self.BtnSeg.setObjectName("BtnSeg")
        self.horizontalLayout_2.addWidget(self.BtnSeg)
        self.BtnBrainSeg = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnBrainSeg.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnBrainSeg.setFont(font)
        self.BtnBrainSeg.setObjectName("BtnBrainSeg")
        self.horizontalLayout_2.addWidget(self.BtnBrainSeg)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnFeature = QtWidgets.QPushButton(self.groupBox_3)
        self.BtnFeature.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnFeature.setFont(font)
        self.BtnFeature.setObjectName("BtnFeature")
        self.horizontalLayout_3.addWidget(self.BtnFeature)
        self.BtnReport = QtWidgets.QPushButton(self.groupBox_3)
        self.BtnReport.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BtnReport.setFont(font)
        self.BtnReport.setObjectName("BtnReport")
        self.horizontalLayout_3.addWidget(self.BtnReport)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.BtnBatch = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBatch.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BtnBatch.setFont(font)
        self.BtnBatch.setToolTipDuration(-1)
        self.BtnBatch.setStyleSheet("margin-left:20;\n"
"margin-right:20;")
        self.BtnBatch.setObjectName("BtnBatch")
        self.verticalLayout_2.addWidget(self.BtnBatch)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionversion = QtWidgets.QAction(MainWindow)
        self.actionversion.setObjectName("actionversion")
        self.actionhelo = QtWidgets.QAction(MainWindow)
        self.actionhelo.setObjectName("actionhelo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BrainRadiomicsTool"))
        self.groupBox.setTitle(_translate("MainWindow", "PreProcessing"))
        self.BtnDicom.setText(_translate("MainWindow", "Dicom2nii"))
        self.BtnReg.setText(_translate("MainWindow", "Registration"))
        self.BtnBet.setText(_translate("MainWindow", "BET"))
        self.BFC.setText(_translate("MainWindow", "BFC/Nor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Segmentation"))
        self.BtnSeg.setText(_translate("MainWindow", "Hippocampus Seg"))
        self.BtnBrainSeg.setText(_translate("MainWindow", "Brain Seg"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Featur Extraction/Analysis"))
        self.BtnFeature.setText(_translate("MainWindow", "Feature"))
        self.BtnReport.setText(_translate("MainWindow", "Report"))
        self.BtnBatch.setToolTip(_translate("MainWindow", "Process a sMRI to produce a Report"))
        self.BtnBatch.setText(_translate("MainWindow", "Batch"))
        self.actionversion.setText(_translate("MainWindow", "version"))
        self.actionhelo.setText(_translate("MainWindow", "help"))

from . import resource_rc
