# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 274)
        Form.setMaximumSize(QtCore.QSize(600, 300))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.RdioSingleFile = QtWidgets.QRadioButton(Form)
        self.RdioSingleFile.setObjectName("RdioSingleFile")
        self.horizontalLayout.addWidget(self.RdioSingleFile)
        self.RadioDir = QtWidgets.QRadioButton(Form)
        self.RadioDir.setObjectName("RadioDir")
        self.horizontalLayout.addWidget(self.RadioDir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.LineImage = QtWidgets.QLineEdit(Form)
        self.LineImage.setMinimumSize(QtCore.QSize(250, 0))
        self.LineImage.setInputMask("")
        self.LineImage.setObjectName("LineImage")
        self.horizontalLayout_2.addWidget(self.LineImage)
        self.BtnImage = QtWidgets.QToolButton(Form)
        self.BtnImage.setMinimumSize(QtCore.QSize(15, 0))
        self.BtnImage.setMaximumSize(QtCore.QSize(20, 16777215))
        self.BtnImage.setObjectName("BtnImage")
        self.horizontalLayout_2.addWidget(self.BtnImage)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.LineRef = QtWidgets.QLineEdit(Form)
        self.LineRef.setMinimumSize(QtCore.QSize(250, 0))
        self.LineRef.setObjectName("LineRef")
        self.horizontalLayout_3.addWidget(self.LineRef)
        self.BtnImage_2 = QtWidgets.QToolButton(Form)
        self.BtnImage_2.setMinimumSize(QtCore.QSize(15, 0))
        self.BtnImage_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.BtnImage_2.setObjectName("BtnImage_2")
        self.horizontalLayout_3.addWidget(self.BtnImage_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.LineResult = QtWidgets.QLineEdit(Form)
        self.LineResult.setMinimumSize(QtCore.QSize(250, 0))
        self.LineResult.setObjectName("LineResult")
        self.horizontalLayout_4.addWidget(self.LineResult)
        self.BtnResult = QtWidgets.QToolButton(Form)
        self.BtnResult.setMinimumSize(QtCore.QSize(15, 0))
        self.BtnResult.setMaximumSize(QtCore.QSize(20, 16777215))
        self.BtnResult.setObjectName("BtnResult")
        self.horizontalLayout_4.addWidget(self.BtnResult)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ProcessBar = QtWidgets.QProgressBar(Form)
        self.ProcessBar.setProperty("value", 24)
        self.ProcessBar.setObjectName("ProcessBar")
        self.verticalLayout.addWidget(self.ProcessBar)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BtnStart = QtWidgets.QPushButton(Form)
        self.BtnStart.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.BtnStart.setFont(font)
        self.BtnStart.setObjectName("BtnStart")
        self.horizontalLayout_5.addWidget(self.BtnStart)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Registration"))
        self.label_4.setText(_translate("Form", "Mode"))
        self.RdioSingleFile.setText(_translate("Form", "Sigle File"))
        self.RadioDir.setText(_translate("Form", "Directory Batch"))
        self.label.setText(_translate("Form", "Source Image"))
        self.LineImage.setText(_translate("Form", "The source Image/Directory Path"))
        self.BtnImage.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Ref Image"))
        self.LineRef.setText(_translate("Form", "If not,use the default Ref MNI 152"))
        self.BtnImage_2.setText(_translate("Form", "..."))
        self.label_3.setText(_translate("Form", "OutputPath"))
        self.LineResult.setText(_translate("Form", "the result Image/Directory Path"))
        self.BtnResult.setText(_translate("Form", "..."))
        self.BtnStart.setText(_translate("Form", "Start!"))

